### ISSUE TITLE
upload profile images

### ISSUE THREAD

**Issue by Slasher4k** [group1URP/gURP1#11]
upload profile image and display in profile

**Comment by emd-che** [comment]
working well for the clients now, i didn't test if for the developers till i add more details and you link it to the skills table then i will make sure that there is no problem though  i checked the code well this time  it should works well,  so you can close the issue.

**Comment by Slasher4k** [comment]
you aren't displaying the uploaded image on the profile, you need to link the storage folder to the public directory.

you can still modify the developer to set no-image for the profile image when the developer is created.

Also you can add links to the edit profile pages as well, possibly on the dashboard at least

**Comment by emd-che** [comment]
they works for me i mean they are displayed in the profiles, and the link to edit profile is exist in the profile page but clients can't edit other people's profiles, i don't know why they r not working for you

**Comment by emd-che** [comment]
maybe the link is local and it's in .gitignore file, that's why it didn't work for you, run php artisan make:link storage in your terminal.
