### ISSUE TITLE
ability for group to cancel project

### ISSUE THREAD

**Issue by Slasher4k** [group1URP/gURP1#6]
Allow the owner of a group to cancel an accepted proposal, with the option of sending a reason why they cancelled.

**Comment by emd-che** [comment]
Where we gonna store the reason? should i make a field for it in the proposal table , what do you think .

**Comment by Slasher4k** [comment]
Don't need to store it, just send the client an email notifying that the group is no longer working on the project and include the reason

**Comment by emd-che** [comment]
Okey, it's a  good chance for me to learn about how to send an email using Laravel!

**Comment by emd-che** [comment]
It should work now but i commented the mail code until we decide how we gonna send them i mean by using  SMPT or using some tools that requires to be installed using composer.
