### ISSUE TITLE
User Profiles

### ISSUE THREAD

**Issue by Slasher4k** [group1URP/gURP1#7]
Setup client and developer profiles and the associated views and controller methods.

**Comment by emd-che** [comment]
Am about to finish all profiles stuff but i wanted to link all new  the new users  to a client table or developer table depending on the "Client/Developer" radio buttons, but  didn't want to touch RegisterController file , i hope you do that.

**Comment by Slasher4k** [comment]
registration controller has been updated

**Comment by Slasher4k** [comment]
just went to work on the developer skills and found that first you had return ('profiles.dev_profile_edit')->with('user', $user); which throws an error need to be return view('profiles.dev_profile_edit')->with('user', $user); so obviously you didn't even test this stuff, secondly the edit page for developers is empty, there was no function in the user controller for the updating of a developer either

**Comment by emd-che** [comment]
i didn't test it obviously because there is nothing to edit, if there any information to edit like in the client  i would of course make sure if it gonna work!
